import { useEffect } from "react";
import { Link } from "react-router-dom";
import { 
    FileText, 
    ShieldAlert, 
    CreditCard, 
    Gavel, 
    Scale, 
    CheckCircle, 
    AlertCircle, 
    ArrowLeft,
    Building2,
    Mail
} from "lucide-react";

function TermsAndConditions() {
    useEffect(() => {
        window.scrollTo({ top: 0, behavior: "smooth" });
    }, []);

    return (
        <div className="w-full bg-[#fafafb] min-h-screen py-6 sm:py-10 px-4 sm:px-6">
            <div className="max-w-4xl mx-auto">
                {/* Navigation Breadcrumb */}
                <div className="mb-6 flex items-center gap-2 text-xs sm:text-sm text-gray-500">
                    <Link to="/" className="flex items-center gap-1 hover:text-[#f37023] transition-colors">
                        <ArrowLeft size={15} /> Home
                    </Link>
                    <span>/</span>
                    <span className="text-[#0c286e] font-semibold">Terms & Conditions</span>
                </div>

                {/* Royal Header Banner */}
                <div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-[#0c286e] via-[#10348a] to-[#0c286e] text-white p-6 sm:p-10 shadow-xl border-2 border-amber-300/40 mb-8">
                    <div className="absolute -right-8 -bottom-8 w-40 h-40 bg-amber-400/10 rounded-full blur-2xl pointer-events-none"></div>
                    <div className="absolute left-1/2 -top-12 -translate-x-1/2 w-64 h-24 bg-[#f37023]/20 rounded-full blur-3xl pointer-events-none"></div>

                    <div className="relative z-10 text-center space-y-3">
                        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-amber-400/15 border border-amber-300/40 text-amber-300 text-xs font-semibold uppercase tracking-wider">
                            ✦ Legal Framework & User Agreement ✦
                        </div>
                        <h1 className="text-2xl sm:text-3xl md:text-4xl font-extrabold tracking-tight">
                            Terms and Conditions of Service
                        </h1>
                        <p className="text-xs sm:text-sm text-amber-100/90 max-w-2xl mx-auto leading-relaxed">
                            Welcome to JP Store. These Terms & Conditions govern your access to and purchase of products on https://www.jpenterprise.store. By accessing our platform, you agree to be bound by these provisions.
                        </p>
                        <p className="text-[11px] text-gray-300 pt-1">
                            Operated by JP Enterprise • Jurisdiction: Rajkot, Gujarat, India
                        </p>
                    </div>
                </div>

                {/* Main Terms Content */}
                <div className="space-y-6 text-gray-800 text-xs sm:text-sm leading-relaxed">

                    {/* Section 1: Introduction & Identity */}
                    <div className="bg-white p-6 sm:p-8 rounded-2xl border border-gray-200 shadow-sm space-y-3">
                        <div className="flex items-center gap-3 border-b border-gray-100 pb-3">
                            <div className="w-8 h-8 rounded-lg bg-orange-100 text-[#f37023] flex items-center justify-center font-bold text-sm">
                                1
                            </div>
                            <h2 className="text-base sm:text-lg font-bold text-[#0c286e]">
                                Entity Details & Acceptance of Terms
                            </h2>
                        </div>
                        <div className="pl-0 sm:pl-11 space-y-2 text-gray-600">
                            <p>
                                This digital document is an electronic record under the <strong className="text-gray-900">Information Technology Act, 2000</strong> and applicable rules thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                            </p>
                            <p>
                                The domain <strong className="text-gray-900">https://www.jpenterprise.store</strong> (&ldquo;Website&rdquo;) is operated by <strong className="text-gray-900">JP Enterprise</strong> (referred to herein as &ldquo;JP Store&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;), having its principal retail establishment at Main Bazaar, Gundala (Jas), Taluka Vinchhiya, District Rajkot, Gujarat - 360055.
                            </p>
                        </div>
                    </div>

                    {/* Section 2: User Eligibility & Account Responsibilities */}
                    <div className="bg-white p-6 sm:p-8 rounded-2xl border border-gray-200 shadow-sm space-y-3">
                        <div className="flex items-center gap-3 border-b border-gray-100 pb-3">
                            <div className="w-8 h-8 rounded-lg bg-orange-100 text-[#f37023] flex items-center justify-center font-bold text-sm">
                                2
                            </div>
                            <h2 className="text-base sm:text-lg font-bold text-[#0c286e]">
                                User Registration, OTP & Account Integrity
                            </h2>
                        </div>
                        <div className="pl-0 sm:pl-11 space-y-2.5 text-gray-600">
                            <p>
                                By creating an account or placing orders on JP Store, you affirm that you are at least 18 years of age or accessing under the supervision of a legal guardian who agrees to these terms.
                            </p>
                            <ul className="list-disc list-inside space-y-1 text-gray-700 pl-1">
                                <li><strong>OTP Authentication:</strong> Registration requires verified email and/or SMS One-Time Passwords (OTP). You are solely responsible for maintaining the secrecy of your login credentials and OTPs.</li>
                                <li><strong>Accurate Delivery Coordinates:</strong> You agree to provide true, accurate, current, and complete details regarding your name, delivery address, phone number, and location pin. Delivering to inaccurate addresses caused by user error will incur additional redelivery costs payable by the customer.</li>
                            </ul>
                        </div>
                    </div>

                    {/* Section 3: Product Pricing, Typographical Errors & Stock */}
                    <div className="bg-white p-6 sm:p-8 rounded-2xl border border-gray-200 shadow-sm space-y-3">
                        <div className="flex items-center gap-3 border-b border-gray-100 pb-3">
                            <div className="w-8 h-8 rounded-lg bg-orange-100 text-[#f37023] flex items-center justify-center font-bold text-sm">
                                3
                            </div>
                            <h2 className="text-base sm:text-lg font-bold text-[#0c286e]">
                                Pricing, Typographical Errors & Merchant Rights
                            </h2>
                        </div>
                        <div className="pl-0 sm:pl-11 space-y-2 text-gray-600">
                            <p>
                                All prices displayed on JP Store are in Indian Rupees (INR) and include applicable taxes (GST) unless specified otherwise. We make every effort to display accurate product photos, technical specifications, and prices.
                            </p>
                            <div className="p-3.5 rounded-xl bg-amber-50 border border-amber-300 text-amber-950">
                                <p className="font-semibold text-xs sm:text-sm mb-0.5">Typographical / Pricing Error Right to Cancel:</p>
                                <p className="text-xs text-amber-900 leading-relaxed">
                                    In the event a product is listed at an incorrect price due to a clerical, technical, or server error, JP Store expressly reserves the right to cancel any orders placed for that item prior to shipment, even if the order was confirmed and payment processed. In such cases, 100% of the charged amount will be reversed immediately through Razorpay.
                                </p>
                            </div>
                        </div>
                    </div>

                    {/* Section 4: Payments & Razorpay Gateway */}
                    <div className="bg-white p-6 sm:p-8 rounded-2xl border border-gray-200 shadow-sm space-y-3">
                        <div className="flex items-center gap-3 border-b border-gray-100 pb-3">
                            <div className="w-8 h-8 rounded-lg bg-orange-100 text-[#f37023] flex items-center justify-center font-bold text-sm">
                                4
                            </div>
                            <h2 className="text-base sm:text-lg font-bold text-[#0c286e] flex items-center gap-2">
                                <CreditCard size={18} className="text-[#f37023]" />
                                Payment Processing via Razorpay
                            </h2>
                        </div>
                        <div className="pl-0 sm:pl-11 space-y-2 text-gray-600">
                            <p>
                                All digital card transactions, UPI payments, net banking, and digital wallets are securely processed through <strong className="text-gray-900">Razorpay Software Private Limited</strong>, an RBI-authorized payment aggregator compliant with PCI-DSS Level 1 standards.
                            </p>
                            <p>
                                By placing an order, you represent and warrant that you have lawful authority to use the payment instrument chosen. JP Store does not store, capture, or have access to your sensitive card CVV numbers, net banking passwords, or UPI MPINs.
                            </p>
                        </div>
                    </div>

                    {/* Section 5: Delivery OTP & Conclusive Acceptance */}
                    <div className="bg-white p-6 sm:p-8 rounded-2xl border border-gray-200 shadow-sm space-y-3">
                        <div className="flex items-center gap-3 border-b border-gray-100 pb-3">
                            <div className="w-8 h-8 rounded-lg bg-orange-100 text-[#f37023] flex items-center justify-center font-bold text-sm">
                                5
                            </div>
                            <h2 className="text-base sm:text-lg font-bold text-[#0c286e]">
                                Doorstep Delivery OTP & Risk of Loss
                            </h2>
                        </div>
                        <div className="pl-0 sm:pl-11 space-y-2 text-gray-600">
                            <p>
                                Title and risk of loss for all purchased merchandise pass to you upon delivery. Our secure courier and local delivery logistics require a secret <strong className="text-gray-900">Delivery OTP</strong> provided only to your registered account.
                            </p>
                            <p>
                                The submission of the Delivery OTP to the courier agent constitutes legally binding proof of physical delivery of the parcel in good outer condition. Customer agrees not to dispute non-receipt once verified OTP has been validated by our logistics system.
                            </p>
                        </div>
                    </div>

                    {/* Section 6: Anti-Scam & Prohibited Misuse */}
                    <div className="bg-white p-6 sm:p-8 rounded-2xl border border-gray-200 shadow-sm space-y-3">
                        <div className="flex items-center gap-3 border-b border-gray-100 pb-3">
                            <div className="w-8 h-8 rounded-lg bg-red-100 text-red-600 flex items-center justify-center font-bold text-sm">
                                6
                            </div>
                            <h2 className="text-base sm:text-lg font-bold text-red-700 flex items-center gap-2">
                                <ShieldAlert size={18} />
                                Strict Anti-Fraud & Prohibited Activities
                            </h2>
                        </div>
                        <div className="pl-0 sm:pl-11 space-y-2 text-gray-600">
                            <p>Users are strictly prohibited from engaging in any of the following activities on our platform:</p>
                            <ul className="list-disc list-inside space-y-1.5 pl-1 text-gray-700">
                                <li>Submitting false, altered, or staged unboxing videos or images to falsely claim refunds.</li>
                                <li>Swapping genuine delivered products with defective, counterfeit, or used items upon return.</li>
                                <li>Initiating bad-faith payment chargebacks with banks after receiving items via verified OTP.</li>
                                <li>Employing automated bots, scraping tools, or DDoS vectors against our servers.</li>
                                <li>Using compromised or stolen credit cards, UPI accounts, or unauthorized payment tokens.</li>
                            </ul>
                            <p className="text-xs text-red-700 pt-1 font-medium">
                                Violation of these rules will result in immediate account termination, blacklisting of phone/address, forfeiture of pending claims, and legal prosecution under the Indian Penal Code (Sections 415, 420 for cheating & fraud) and the IT Act 2000.
                            </p>
                        </div>
                    </div>

                    {/* Section 7: Limitation of Liability */}
                    <div className="bg-white p-6 sm:p-8 rounded-2xl border border-gray-200 shadow-sm space-y-3">
                        <div className="flex items-center gap-3 border-b border-gray-100 pb-3">
                            <div className="w-8 h-8 rounded-lg bg-orange-100 text-[#f37023] flex items-center justify-center font-bold text-sm">
                                7
                            </div>
                            <h2 className="text-base sm:text-lg font-bold text-[#0c286e]">
                                Limitation of Liability & Warranty Disclaimer
                            </h2>
                        </div>
                        <div className="pl-0 sm:pl-11 space-y-2 text-gray-600">
                            <p>
                                Products sold on JP Store carry their respective original manufacturer warranties where applicable (e.g. Samsung, boAt, Apple, Realme, Xiaomi). JP Store does not provide separate independent product warranties beyond authentic origin assurance and our standard 48-hour transit damage replacement policy.
                            </p>
                            <p>
                                In no event shall JP Enterprise, its directors, or affiliates be liable for indirect, punitive, incidental, or consequential damages resulting from product use or delayed delivery. Our total liability for any claim shall strictly not exceed the purchase price paid for the specific item in dispute.
                            </p>
                        </div>
                    </div>

                    {/* Section 8: Governing Law & Jurisdiction */}
                    <div className="bg-white p-6 sm:p-8 rounded-2xl border border-gray-200 shadow-sm space-y-3">
                        <div className="flex items-center gap-3 border-b border-gray-100 pb-3">
                            <div className="w-8 h-8 rounded-lg bg-orange-100 text-[#f37023] flex items-center justify-center font-bold text-sm">
                                8
                            </div>
                            <h2 className="text-base sm:text-lg font-bold text-[#0c286e] flex items-center gap-2">
                                <Gavel size={18} className="text-[#f37023]" />
                                Governing Law & Exclusive Jurisdiction
                            </h2>
                        </div>
                        <div className="pl-0 sm:pl-11 space-y-2 text-gray-600">
                            <p>
                                These Terms shall be governed by, construed, and enforced in accordance with the substantive laws of the Republic of India.
                            </p>
                            <p>
                                Any dispute, claim, or controversy arising out of or in connection with transactions on JP Store shall be subject to the <strong className="text-gray-900">exclusive jurisdiction of the competent courts in Jasdan / Rajkot, Gujarat, India</strong>.
                            </p>
                        </div>
                    </div>

                    {/* Section 9: Grievance Officer */}
                    <div className="bg-gradient-to-r from-orange-50 via-white to-amber-50 p-6 sm:p-8 rounded-2xl border border-amber-300 shadow-sm space-y-3">
                        <div className="flex items-center gap-2 text-[#0c286e] font-bold text-base">
                            <Building2 size={18} className="text-[#f37023]" />
                            Grievance Redressal & Legal Notices
                        </div>
                        <p className="text-gray-600">
                            In accordance with the Information Technology Act, 2000 and Consumer Protection (E-Commerce) Rules, 2020, the contact details of the Grievance Officer are provided below:
                        </p>
                        <div className="text-xs sm:text-sm text-gray-800 space-y-1 pt-1">
                            <p><strong>Designation:</strong> Grievance & Compliance Officer</p>
                            <p><strong>Entity:</strong> JP Enterprise (JP Store)</p>
                            <p><strong>Address:</strong> Main Bazaar, Gundala (Jas), Taluka Vinchhiya, District Rajkot, Gujarat - 360055, India</p>
                            <p><strong>Email:</strong> <a href="mailto:support@jpenterprise.store" className="text-[#f37023] font-semibold underline">support@jpenterprise.store</a></p>
                            <p><strong>Escalation Phone:</strong> +91 98765 43210 (10:00 AM – 6:00 PM IST, Monday to Saturday)</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    );
}

export default TermsAndConditions;
